### ISSUE TITLE
Is it possible to run this pipeline in a cluster without internet?

### ISSUE THREAD

**Issue by scienception** [PGScatalog/pgsc_calc#120]
### Description of feature

I managed to install nextflow with all its dependencies in this "private" cluster. But now I'm not sure how to run this pipeline without internet access. Is this at all possible?

**Comment by nebfield** [comment]
Yes, people have used `pgsc_calc` in offline environments. 

If you can run the test profile on your private cluster, then you've already managed to [preload the containers we use](https://pgsc-calc.readthedocs.io/en/latest/reference/containers.html#singularity), which is great 😄 

You need to manually download scoring files from the PGS Catalog and move them to your private cluster. You could try the `download_scorefiles` program in our [`pgscatalog_utils` package](https://github.com/PGScatalog/pgscatalog_utils). This program makes it simpler to download multiple scoring files at the same time in the correct genome build but there's no nice documentation yet (we use this package as an internal tool inside `pgsc_calc`). You could also manually download scoring files in the correct genome build from the PGS Catalog FTP.

Once you've transferred these files to your private cluster, you can set:

 `--scorefile "path/to/scorefiles.txt.gz"`

instead of `--pgs_id` or `--trait_efo` (the `"` quotes are important for `--scorefile`).

You'll also need to preload some small reference data described here: https://github.com/PGScatalog/pgsc_calc/issues/66#issuecomment-1339573297 and set the `--ref` parameter to the local file path. 

Good luck!

**Comment by scienception** [comment]
I am running it this way:
./nextflow-23.04.2-all run pgsc_calc/main.nf -profile test,singularity --ref pgsc_calc_ref.sqlar

However I get this error:
ERROR ~ Unable to read script: '/users/myuser/pgsc_calc/./workflows/pgscalc.nf' -- cause: https://gitlab.ebi.ac.uk/nebfield/test-datasets/-/raw/master/pgsc_calc/samplesheet.csv

The path of pgsc_calc_ref.sqlar is fine. Not sure what I'm doing wrong.

**Comment by scienception** [comment]
Never mind I got it working like this:

`./nextflow-23.04.2-all run pgsc_calc/main.nf -profile test,singularity --input /users/myuser/pgsc_calc/assets/examples/samplesheet.csv --scorefile /users/myuser/pgsc_calc/assets/examples/scorefiles/scorefile.txt --ref pgsc_calc_ref.sqlar`

and updating the samplesheet.csv with the correct path.

Thank you so much for your help by the way :) I truly appreciate it.

**Comment by nebfield** [comment]
Great! We'll improve the offline documentation next release 😄  (#9)

**Comment by DarioS** [comment]
Typically, a cluster will have a few nodes assigned to a data transfer queue role and perhaps you could easily run it there.
