### ISSUE TITLE
PGS using all chromosomes for matching to target

### ISSUE THREAD

**Issue by scienception** [PGScatalog/pgsc_calc#124]
Hi! I initially was getting an error saying that only 8% of the variants between PGS and my target genomic data matched. In my sample sheet I had specified that I only wanted chr 1 (which refers to the the target).
The PGS file contains chromosomes 1 up to 22. Once I removed the rest of chromosomes (leaving only chr 1) the pipeline completed succesfully. 
My target data consists of 7402792 chr 1 variants and the PGS of 53050 chr 1 variants (648559 in total counting other chromosomes).
I'm guessing the computation is using all chromosomes though. Is there a reason for this? Shouldn't you filter out the rest of the chromosomes in the base file too?

Note: I downloaded the PGS from the PGS catalog (wget https://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000001/ScoringFiles/Harmonized/PGS000001_hmPOS_GRCh37.txt.gz) and made sure they were in the correct genome build.

**Comment by nebfield** [comment]
If I understand correctly you're trying to calculate a PGS that includes variants from chromosomes 1-22 for a target genome that consists of a single chromosome. Trying to do this causes `pgsc_calc` to return an error about match rates.

This is expected behaviour and a good error. `pgsc_calc` won't filter scoring files if you only use a subset of chromosomes as input target genomes.

The aim of `pgsc_calc` is to reproduce scores published in the PGS Catalog. To reliably reproduce scores we have to use all the variants that the authors describe in the scoring file (or as many as possible). If we don't do this, then we're not reproducing the author's score, and the predictive performance of the score won't match what the authors have reported. 

I hope that makes sense. Please let me know if I haven't understood your question correctly 😄

**Comment by scienception** [comment]
The thing is that the .pgen files are separated by chromosome. How could I give all the chromosomes at once then?

imp_chr1_v2.psam
imp_chr1_v2.pgen
imp_chr1_v2.pvar
imp_chr2_v2.psam
imp_chr2_v2.pgen
imp_chr2_v2.pvar
imp_chr3_v2.psam
imp_chr3_v2.pgen
imp_chr3_v2.pvar
imp_chr4_v2.psam
imp_chr4_v2.pgen
imp_chr4_v2.pvar
.
.
.
Should I join them all first and create single .pgen file?

**Comment by scienception** [comment]
You're the best! Thanks :) I promise I will read the documentation more thoroughly next time 😅
