### ISSUE TITLE
Check sampleset ID doesn't include and underscore (_)

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgsc_calc#272]
https://github.com/PGScatalog/pgsc_calc/blob/8bdf287d558a7abe1ef86e961337df71d7289d0d/lib/SamplesheetParser.groovy#L175-L182

This module needs to check for reserved names as was done in the old sample sheet checking (no 'reference' or '_'): https://github.com/PGScatalog/pgscatalog_utils/blob/6da7eb0e157ba4e73f941233ee8d8ae4fb5e3926/pgscatalog_utils/samplesheet/check.py#L306-L322

**Comment by smlmbrt** [comment]
Fixed in https://github.com/PGScatalog/pgsc_calc/commit/954330a27f2bd7763080c1bcc5fb593387fff62d

**Comment by Carldeboer** [comment]
I just encountered this bug and it is super confusing to have an error message "Reserved sampleset name detected. Please don't call your sampleset 'reference'" when the issue is actually that the sampleset name contains an underscore character. Took me hours of trial and error to determine that this was the cause. @nebfield

**Comment by smlmbrt** [comment]
@Carldeboer, we'll fix it to make it more specific. That's an omission on our part.

**Comment by Carldeboer** [comment]
thanks!
