### ISSUE TITLE
Plink Error: chrX is present in the input file, but no sex information was provided

### ISSUE THREAD

**Issue by gajamatassa** [PGScatalog/pgsc_calc#340]
### Description of the bug

Hi,

thank you for your amazing pipeline!

I am writing to you because using the latest release (v2.0.0-beta.1) I got this error:

```
  Error: chrX is present in the input file, but no sex information was provided;
  rerun this import with --psam or --update-sex.  --split-par may also be
  appropriate.
```

during the execution of the process 'PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF 

It is a plink error, maybe`--allow-extra-chr` is not the correct parameter to use in plink2? (https://www.biostars.org/p/9593855/).

I am giving to the pipe a vcf as input.

I do not understand why this error occurred with the new release. I have recently run an older version (v2.0.0-alpha.5, same command and input file) and everything worked smoothly.

Do you have any idea about how to solve this issue?

Thank you a lot!

### Command used and terminal output

```console
nextflow run pgscatalog/pgsc_calc -profile singularity -latest --input samplesheet.csv --target_build GRCh38 --pgs_id PGS003724,PGS002746,PGS002135
```

### System information

Nextflow version: 23.10.1
Executor: local
Container engine: Singularity
OS: Linux
Version of pgsc_calc: v2.0.0-beta.1

**Comment by smlmbrt** [comment]
Hi @gajamatassa, if you know the sex I would suggest converting your VCFs into plink2 format files using plink outside our pipeline (https://pgsc-calc.readthedocs.io/en/latest/how-to/prepare.html#vcf-from-an-imputation-server) for chr 1. Then adding sex information into the resultant .psam file, and next re-running the conversion with --psam specfied for all chromosomes and using those plink2 files as input instead of the VCF. This should explicitly code sex and not throw a warning. 

If the PGS you're planning on calculating do not include X chromosome I would just drop it from the input and it should run fine. As the biostar comment states: this is due to better data checks in plink2 (which we recently upgraded in the pipeline).

**Comment by gajamatassa** [comment]
Thanks for your answer!

I'll try and let you know.

**Comment by Fiwx** [comment]
I also got this error (using differently formatted vcf file). When I ran the plink2 command manually, it worked correctly. I am not sure why it creates this error when pgsc_calc runs the same command, but works when I run it. This is not an issue since I will not format my files in this problematic way, but it may be good to know.

**Comment by smlmbrt** [comment]
@Fiwx, it's probably because the release of plink2 you're using is older than the release in the pipeline. We updated to use plink-2.00a5.10 as there were some bug fixes implemented that we thought might be useful for our application.
