### ISSUE TITLE
PGS scores from a large population?

### ISSUE THREAD

**Issue by zhongwang** [PGScatalog/pgsc_calc#85]
Hi,

This is more of a question than an issue. I am developing a Apache Spark-based solution to compute PGS, which may compute all 3000 PGS for 2500 1kgenomes in minutes. I was wondering if you have done sth similar, or do you have any recommendation for larger, public genome datasets? I am interested to compare the results as part of a potential publication. I could try to do this using pgsc_calc, but wasn't able to pull a file from GitLab. Thanks. --Zhong

**Comment by nebfield** [comment]
Hi Zhong,

We were experiencing an issue with out GitLab instance that broke new installs over the weekend, sorry!  See 
https://github.com/PGScatalog/pgsc_calc/issues/84 The issue is fixed now and you should be able to install the workflow.

We do run `pgsc_calc` on UK Biobank (500,000) with the largest traits on the PGS Catalog but this is controlled access data. For large scale public data I can recommend the new [HAPNEST](https://www.ebi.ac.uk/biostudies/studies/S-BSST936) synthetic dataset, which contains about 1 million individuals and about 7 million variants. Real data will normally contain many more variants, however.

@smlmbrt will be able to provide more context about scaling PGS calculation to large datasets 😄 

Thanks,
Ben

**Comment by smlmbrt** [comment]
It's also worth noting that the most significant run-time of our program is the steps to download, reformat, and match variants in scoring files to the genome (which scales with total # of variants rather than PGS). The actual scoring step is short and runs within plink (which might be a more relevant comparison).

**Comment by zhongwang** [comment]
Thanks! I'll give it a try.
